<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Megaraz.ResultPattern</PackageId>
    <Title>Megaraz Result Pattern</Title>
    <Description>A focused Result Pattern library for .NET.</Description>
    <Authors>Megaraz</Authors>
    <RepositoryUrl>https://github.com/Megaraz/Megaraz.ResultPattern</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>result;result-pattern;errors;validation</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
